# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuber-express
  template:
    metadata:
      labels:
        app: kuber-express
    spec:
      containers:
        - name: kuber-express
          image: shubhchoubey8/kuber-express:latest
          ports:
            - containerPort: 3000
